FB-1: Верстка главной страницы
frontend-park-mail-ru/2020_2_Slash pull request #2
Opened 2020-09-16 20:05 UTC by yletamitlu

Вопросы: 
1. Не до конца понятны некоторые вещи с position (делала по примерам, не поняла до конца существует ли истинная схема)
2. Нормально ли использовать для адаптивности vw ?
3. Все ли окей с точки зрения БЭМа и логических блоков в html ?
4. Не поборола футер, что с ним можно сделать? (не могу позиционировать его внизу страницы после всего контента)
5. Вопрос по поводу градиента - для хэдера сделала нормально, а для превью из-за абсолютного позиционирования пришлось делать отдельным дивом, как быть ? И этот градиент работает только в фуллскрине((

2020-09-16 23:24 UTC, yletamitlu commented
> Вопросы:
> 
> 1. Не до конца понятны некоторые вещи с position (делала по примерам, не поняла до конца существует ли истинная схема)
> 2. Нормально ли использовать для адаптивности vw ?
> 3. Все ли окей с точки зрения БЭМа и логических блоков в html ?
> 4. Не поборола футер, что с ним можно сделать? (не могу позиционировать его внизу страницы после всего контента)
> 5. Вопрос по поводу градиента для превью - как его сделать нормально?)))

2020-09-16 23:24 UTC, yletamitlu commented
> > Вопросы:
> > 
> > 1. Не до конца понятны некоторые вещи с position (делала по примерам, не поняла до конца существует ли истинная схема)
> > 2. Нормально ли использовать для адаптивности vw ?
> > 3. Все ли окей с точки зрения БЭМа и логических блоков в html ?
> > 4. Не поборола футер, что с ним можно сделать? (не могу позиционировать его внизу страницы после всего контента)
> > 5. Вопрос по поводу градиента для превью - как его сделать нормально?

2020-09-16 23:29 UTC, yletamitlu commented
> > > Вопросы:
> > > 
> > > 1. Не до конца понятны некоторые вещи с position (делала по примерам, не поняла до конца существует ли истинная схема)
> > > 2. Нормально ли использовать для адаптивности vw ?
> > > 3. Все ли окей с точки зрения БЭМа и логических блоков в html ?
> > > 4. Не поборола футер, что с ним можно сделать? (не могу позиционировать его внизу страницы после всего контента)
> > > 5. Вопрос по поводу градиента для превью - как сделать его нормально? Потому что превью отдельным дивом плохо работает, а как с хэдером сделать не получается, потому что фон превью позиционирован абсолютно - как быть?

2020-09-17 11:29 UTC, StealthTech requested changes

2020-09-17 11:29 UTC, StealthTech commented on public/css/index.css
> +a {
Для стилей лучше не использовать селекторы по тэгам. Это может при увеличении масштабов проекта мешать стилизовывать нужные блоки на странице — лучше создать класс

2020-09-17 11:29 UTC, StealthTech commented on public/css/index.css
> +.play-btn > img, .info-btn > img {
Вот так тоже не стоит делать. Вдруг тнбе понадобится изменить вложенность?

2020-09-17 11:29 UTC, StealthTech commented on public/css/vars.css
> +    --main-color: #141414;
Круто, что заюзала css custom properties!

2020-09-17 11:29 UTC, StealthTech commented on public/index.html
> +<!--    <div class="footer">-->
Закомментированных кусков кода быть не должно

2020-09-17 11:29 UTC, StealthTech commented on public/css/index.css
> +@media (max-width: 850px) {
Круто, что ты начала делать адаптив, но это можно отложить  до третьего РК

2020-09-19 20:11 UTC, StealthTech approved these changes

2020-09-19 20:14 UTC, merged