FB-51: Добавить webpack, добавить handlebars-loader - поправить все ф…
frontend-park-mail-ru/2020_2_Slash pull request #23
Opened 2020-10-10 15:28 UTC by yletamitlu

…айлы, поправить путь к статике в сервере - поправить все файлы

2020-10-10 15:44 UTC, StealthTech commented on webpack.config.js
> +        filename: 'bundle.js',
Сюда лучше добавить `hash`

2020-10-10 15:44 UTC, StealthTech commented on webpack.config.js
> +                exclude: /(node_modules|bower_components)/
А почему такой интересный exclude?

2020-10-10 15:44 UTC, StealthTech commented on package.json
> +    "dev": "webpack",
На продакшене должна быть `production` версия. Под нее хорошо бы иметь `npm run build`. И `dev` не говорящее название

2020-10-10 15:44 UTC, StealthTech commented on webpack.config.js
> +                { from: './public/img', to: 'img' },
Хм, а почему так?

2020-10-10 15:44 UTC, StealthTech commented on src/consts/settings.js
> +export const SERVER_HOST = 'http://188.166.99.23:8001';
Это ничего не сломает в интеграции с бекендом?

2020-10-10 23:51 UTC, yletamitlu commented on webpack.config.js
> +                exclude: /(node_modules|bower_components)/
bower_components - случайно вставила из документации..не нужен

2020-10-11 14:19 UTC, StealthTech requested changes

2020-10-11 14:19 UTC, StealthTech commented on webpack.config.js
> +                exclude: /(node_modules)/
А разве где-то в node_modules есть .hbs файлы?

2020-10-11 14:19 UTC, StealthTech commented on webpack.config.js
> +                use: [MiniCssExtractPlugin.loader, 'css-loader'],
Почему не style-loader? Он вроде был к месту

2020-10-11 15:09 UTC, StealthTech submitted a review, later dismissed

2020-10-11 15:15 UTC, StealthTech approved these changes

2020-10-11 15:15 UTC, merged