FB-44: Cделать интерфейс плеера
frontend-park-mail-ru/2020_2_Slash pull request #25
Opened 2020-10-14 00:57 UTC by yletamitlu

2020-10-14 11:03 UTC, StealthTech requested changes

2020-10-14 11:03 UTC, StealthTech commented on src/components/MainTab/MainTab.hbs
> +                <p class="misc-item_rating misc-item">{{rating}}</p>
Не по БЭМ, модификаторы вместо элементов

2020-10-14 11:03 UTC, StealthTech commented on src/components/Player/Player.js
> +        super({parent: parent, context: context});
`{parent, context}`

Не обязательно повторять ключ/значение, если они равны

2020-10-14 11:03 UTC, StealthTech commented on src/components/Player/Player.js
> +    render() {
Может быть, эту функцию можно вынести в `BaseComponent`?

2020-10-14 11:03 UTC, StealthTech commented on src/controllers/IController.ts
> +interface IController{
Пробел

2020-10-14 11:03 UTC, StealthTech commented on src/controllers/IController.ts
> +import CustomObject from '../tools/customInterfaces/customObject'
Не понимаю, что есть `CustomObject`?

2020-10-14 11:03 UTC, StealthTech commented on src/controllers/PlayerController.ts
> +        let playerService = new PlayerService();
Ага! Не `let`, а `const`!

2020-10-14 11:03 UTC, StealthTech commented on src/controllers/PlayerController.ts
> +        const data1: CustomObject = {
`data1` — неудачное название. Лучше назвать как-нибудь семантически правильно, описывая суть. А вообще тут можно сразу аргументом в `insertIntoContext`

2020-10-14 11:03 UTC, StealthTech commented on src/controllers/PlayerController.ts
> +    switchOn(data: CustomObject) {
`data` не используется?

2020-10-14 11:03 UTC, StealthTech commented on src/controllers/PlayerController.ts
> +        this.onSwitchOn({})
Пустой объект?

2020-10-14 11:03 UTC, StealthTech commented on src/controllers/TBaseController.ts
> +    onSwitchOn(data: CustomObject) {}
`onSwitchOn` — может быть, придумаем что-то, чтобы не было `on` два раза?

2020-10-14 11:03 UTC, StealthTech commented on src/index.css
> +@import "views/PlayerView/PlayerView.css";
Давай отсортируем импорты :) Пусть `views` будет после `controllers`

2020-10-14 11:03 UTC, StealthTech commented on src/index.js
>      .start();
Есть предложение, чтобы не копипастить `.register`, сделать объект вида `{route: controller}` и передавать его в `.start`. А внутри `start` уже все роуты зарегистрировать, как надо

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        let progressBar = document.querySelector('.player__scrubber-bar');
`const`

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +            "/static/img/player-pause.svg", "videoPause");
Кавычки

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        // @ts-ignore
Почему?

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        let currentTime = currentPosition / width;
`const`

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        progressBar.setAttribute('value', (currentTime).toString());
Зачем скобки?

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        this.video.currentTime = this.video.duration * (currentTime);
Зачем скобки?

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        if (!isPause) this.video.play();
Лучше не делать так, хотя это и валидно с точки зрения синтаксиса. Лучше читается, когда в фигурных скобках и с переносом на новую строку

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        this.video = document.querySelector('.video');
В геттер вынести, может?

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        let currentTime = currentPosition / width;
У меня дежа вю. Давай повторяющиеся части кода выносить в отдельные функции/методы

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        let progressBar = document.querySelector('.player__scrubber-bar');
`const`. Прогляди весь новый код на предмет этого, пожалуйста

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        document.head.appendChild(style);
![image](https://user-images.githubusercontent.com/5190765/95979529-70dbda00-0e24-11eb-9bcf-7daabf67adbd.png)

Вот здесь проблема

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        style.innerHTML = `.player__scrubber-bar:hover:before {
Интересный хак. Почему нельзя здесь указать только то, что динамически меняется?
Если нужно будет в итоге оставить здесь шаблонную строку, давай отформатируем. 
![image](https://user-images.githubusercontent.com/5190765/95979787-dc25ac00-0e24-11eb-95c7-463b736bed5f.png)

И `::before`, `::after`

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        let currentVolume = currentPosition / width;
Аналогичные замечания здесь и далее по коду

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        let d = setTime(duration)
`let d` — не делаем

2020-10-14 11:03 UTC, StealthTech commented on src/services/PlayerService.ts
> +        let p = document.querySelector('.player-bar__time');
`let p` — не делаем. надо нормальные названия

2020-10-14 11:03 UTC, StealthTech commented on src/tools/customInterfaces/customObject.ts
> +    [key: string]: any
Зачем этот интерфейс нужен? Это же практически то же самое, что обычный объект без интерфейса :)

2020-10-14 11:03 UTC, StealthTech commented on src/tools/time.ts
> +export default function setTime(inputSeconds: number) {
Почему не стрелочная?

2020-10-14 11:03 UTC, StealthTech commented on src/tools/time.ts
> +        time = (hours*10/10).toFixed(0).toString() + ' : '
В современном JS есть шаблонные строки, которые ты ранее уже использовала. Скопировала откуда-то? Давай адаптируем по-нормальному

2020-10-14 11:03 UTC, StealthTech commented on src/tools/time.ts
> +    let hours = Math.floor(inputSeconds/3600);
`const`

2020-10-14 11:03 UTC, StealthTech commented on src/tools/time.ts
> +    if (minutes < 0) minutes = - minutes;
Давай сделаем переносы

2020-10-14 11:03 UTC, StealthTech commented on src/views/IView.ts
> +    setContext(inputContext: CustomObject): void;
Если нужен интерфейс контекста, который ограничивает значения, это имеет смысл. А так — это просто любой объект

2020-10-14 11:03 UTC, StealthTech commented on src/views/PlayerView/PlayerView.css
> +.watch_page {
БЭМ

2020-10-14 11:03 UTC, StealthTech commented on src/views/PlayerView/PlayerView.ts
> +                title: title,
`{title}`

2020-10-14 11:03 UTC, StealthTech commented on src/views/TBaseView.ts
> +    constructor(title?: string, template?: any, context?: CustomObject) {
Если все параметры опциональны, лучше засунуть их в объект, для которого сделать свой интерфейс и деструктуризацию

2020-10-14 11:03 UTC, StealthTech commented on webpack.config.js
> +        extensions: [ '.tsx', '.ts', '.js' ],
Откуда у вас этот `.tsx`?)

2020-10-14 11:03 UTC, StealthTech commented on webpack.config.js
> +                test: /\.tsx?$/,
`tsx`

2020-10-14 16:29 UTC, yletamitlu commented on src/controllers/PlayerController.ts
> +    switchOn(data: CustomObject) {
не-а

2020-10-14 16:33 UTC, yletamitlu commented on src/controllers/PlayerController.ts
> +        this.onSwitchOn({})
да, по базовому классу нужно, чтобы был объект в аргументах (так как потом все контроллеры перепишутся на тайпскрипт и там уже есть контроллеры в непустой датой в аргументах, которая используется)
здесь возможно тоже может быть будут какие-то данные потом, а может нет, но пока что ничего не надо передавать
а ничего не передать нельзя

2020-10-14 16:39 UTC, yletamitlu commented on src/services/PlayerService.ts
> +        // @ts-ignore
ide почему-то не воспринимает clientX, но это работает, и можно такой комментарий оставить, чтобы он не ругался

2020-10-14 16:47 UTC, yletamitlu commented on webpack.config.js
> +        extensions: [ '.tsx', '.ts', '.js' ],
без него не заводится

2020-10-14 19:57 UTC, yletamitlu commented on src/tools/customInterfaces/customObject.ts
> +    [key: string]: any
а как тогда хранить в TS объекте поля разного типа?

2020-10-15 18:39 UTC, StealthTech requested changes

2020-10-15 18:39 UTC, StealthTech commented on src/controllers/PlayerController.ts
> +    switchOn(data: CustomObject) {
Надо выпилить тогда!

2020-10-15 18:39 UTC, StealthTech commented on src/controllers/PlayerController.ts
> +        this.onSwitchOn({})
Если есть кейсы, где передается пустой объект, нужно модифицировать метод, чтобы он мог вызываться без аргументов

2020-10-15 18:39 UTC, StealthTech commented on src/services/PlayerService.ts
> +        timelineMiddle.style.width = `${0}%`;
што

2020-10-15 18:39 UTC, StealthTech commented on src/services/PlayerService.ts
> +        const btnBack: any = document.querySelector('.watch__back-btn');
Вместо any лучше уж ничего. Тогда ts сам выведет тип

2020-10-15 18:39 UTC, StealthTech commented on src/services/Router.js
> +        console.log(EventBus.listeners)
!

2020-10-15 18:39 UTC, StealthTech commented on src/tools/time.ts
> +        time = toStr(hours) + ':' + toStr(minutes) + ':' + toStr(seconds);
Шаблонные строки

2020-10-15 18:39 UTC, StealthTech commented on src/tools/time.ts
> +            return '0' + ((input*10)/10).toFixed(0).toString();
Шаблонные строки! И чего с пробелами(

2020-10-15 18:39 UTC, StealthTech commented on src/tools/time.ts
> +    function toStr(input: any): any {
Стрелочная функция

2020-10-15 21:16 UTC, StealthTech commented on src/tools/customInterfaces/customObject.ts
> +    [key: string]: any
Просто не указывай ему тип?

2020-10-16 10:12 UTC, StealthTech approved these changes

2020-10-16 10:12 UTC, merged