Registration page layout fb 12
frontend-park-mail-ru/2020_2_Slash pull request #4
Opened 2020-09-21 16:30 UTC by butoly

2020-09-22 20:21 UTC, StealthTech requested changes

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +.registration-page {
![image](https://user-images.githubusercontent.com/5190765/93932334-b1b26880-fd28-11ea-942d-9262b06b34bb.png)

С версткой что-то не так :(

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +.registration-page {
Попап уехал к нижней границе экрана, хотя предполагался по центру. Инпуты должны быть на всю ширину попапа плюс паддинги от краёв. Я бы увеличил расстояние до заголовка попапа пикселей на 5-10. Снизу текст совершенно не читается. Я помню, что говорил сделать попап пошире, но кажется, что теперь он совсем широкий — я бы сделал его уже на ширину одной боковой "колонки"

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +    position:fixed;
После двоеточия принято ставить пробелы

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +    left:50%;
Я бы сделал контейнер, который растянул на весь экран через height и width 100%. Затем ему же сделал display: flex; align-items: center; justify-content: center. И в него поместил сам попап. Тогда он автоматически будет по центру, и не придется делать такие хитрые штуки с процентами

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +    margin-left: -15%;
Отрицательные отступы — зло, не стоит их использовать. Почти всегда можно обойтись без них

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +    max-height: 421px;
Почему именно такие числа? Кажется, что здесь выверять попиксельно плохая идея

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +.registration-page form {
Не стоит вешать стили на селекторы по тэгам. Для этого лучше завести класс. Например, по методологии БЭМ (https://ru.bem.info/) это будет `.registration-page__form`

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +form h1 {
Аналогично про БЭМ

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +    font-family: Helvetica Neue;
Лучше бы повесить куда-нибудь на корневой элемент. Стили применятся каскадно и будет счастье!

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +    font-weight: normal;
Почему так? Хм.

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +    line-height: 114.3%;
Ёлки-иголки, почему здесь дробные проценты?

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +    width: 289px;
Стараемся избавляться от магических чисел. Почему не 300px? Пройдись и поправь везде, пожалуйста

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +    margin: auto;
Хм. А зачем?

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +.signin p {
Везде нужно убрать селекторы по тэгам. Делаем только через классы

2020-09-22 20:21 UTC, StealthTech commented on public/registration.html
> +    <link rel="stylesheet" href="css/index.css">
А чего тут без type?

2020-09-22 20:21 UTC, StealthTech commented on public/registration.html
> +                <p>Уже зарегистрированы? <a href="javascript:PopUpHide()">Войти.</a></p>
`javascript:PopUpHide()`?

2020-09-22 20:21 UTC, StealthTech commented on public/registration.html
> +    <div class="registration-page">
Я так понимаю, предполагается, что регистрация всегда будет попапом. Тогда стоит назвать класс как `-popup` или `-modal`

2020-09-22 20:21 UTC, StealthTech commented on public/registration.html
> +<div class="application">
Т.к. решили делать регистрацию попапом, верстку до registration-page не смотрю. Предполагаю, что вы её удалите, когда будете делать SPA

2020-09-22 20:21 UTC, StealthTech commented on public/css/registration.css
> +.inputs-container button{
Следим за пробелами. `button {`

2020-09-23 00:58 UTC, butoly commented
Вопросиксы:
1) Нормально ли это использовать `position: fixed` и `top: X%`  чтобы поднять попап наверх?
2) Ширину попапа задаю в процентах `width: 23%;`, или надо пикселями?
3) Я понял как контролить ширину элементов(например для инпута мы задаем `width: 100%`  и делаем `padding`), а что делать с высотой элементов(тех жи инпутов) у меня там везде захардкожено в пикселях?
4) Почему шрифт в кнопке не наследуется со свойств предка тега?
5) Кнопка плавает, не могу понять почему. 
<img width="1792" alt="Снимок экрана 2020-09-23 в 03 51 28" src="https://user-images.githubusercontent.com/31550348/93952083-a6733300-fd50-11ea-959a-b5b46f3062e4.png">
      
![Снимок экрана 2020-09-23 в 03 51 51 (2)](https://user-images.githubusercontent.com/31550348/93952149-d0c4f080-fd50-11ea-8bb6-f819ad58cf57.png)

2020-09-23 09:33 UTC, StealthTech requested changes
Не на все старые замечания отреагировал. Ответы на вопросы оставил в чате в телеграме

2020-09-23 09:33 UTC, StealthTech commented on public/css/registration.css
> +.signin__a {
Неправильное именование — нужно писать, что это по смыслу. Например, `link` бы подошло, потому что ясно, что это ссылка. И тега link в верстке не может быть

2020-09-23 09:33 UTC, StealthTech commented on public/css/registration.css
> +.signin__p {
Аналогично, надо называть по смыслу, а не по названию тега

2020-09-23 09:33 UTC, StealthTech commented on public/css/registration.css
> +    width: 23%;
Давай откажемся от верстки через проценты (кроме тех мест, где нужно 100%), а то больно уж попал скукоживает при таком

2020-09-23 09:33 UTC, StealthTech commented on public/css/registration.css
> +    width: 80%;
Лучше не так, а через padding/margin

2020-09-23 09:33 UTC, StealthTech commented on public/css/registration.css
> +    margin-left: 10%;
Вот тут собака зарыта — margin лучше делать в пикселях

2020-09-23 09:33 UTC, StealthTech commented on public/css/registration.css
> +.popup-container {
Текст снизу попапа всё еще не читается. Давай сделаем его ярче, а то тут же темно-серый на почти черном!

2020-09-23 19:13 UTC, StealthTech requested changes
Вооооот, теперь то что надо! Давай добавим type и поправим класс, что осталось в моих комментариях, и проставлю аппрув!

2020-09-23 19:13 UTC, StealthTech commented on public/css/registration.css
> +.registration-page__h1 {
То же самое про БЭМ

2020-09-23 20:47 UTC, StealthTech approved these changes

2020-09-23 20:48 UTC, merged