FB-109: Сделать всплытие поисковой строки
frontend-park-mail-ru/2020_2_Slash pull request #52
Opened 2020-11-20 19:56 UTC by yletamitlu

2020-11-20 20:13 UTC, StealthTech requested changes

2020-11-20 20:13 UTC, StealthTech commented on src/components/Header/Header.hbs
> +        <img class="header__search-img control__item" src="/static/img/search.svg"></button>
Проблемы с отступом

2020-11-20 20:13 UTC, StealthTech commented on src/components/SearchInput/SearchInput.hbs
> +    <a href="" class="search-line__href" data-event="">
Эта ссылка будет вести куда-то?

2020-11-20 20:13 UTC, yletamitlu commented on src/components/SearchInput/SearchInput.hbs
> +    <a href="" class="search-line__href" data-event="">
да, в след тикетах

2020-11-20 20:17 UTC, StealthTech submitted a review, later dismissed

2020-11-21 10:14 UTC, StealthTech approved these changes

2020-11-21 10:14 UTC, merged