Main page to spa fb 16
frontend-park-mail-ru/2020_2_Slash pull request #6
Opened 2020-09-28 23:29 UTC by yletamitlu

2020-09-29 22:25 UTC, StealthTech requested changes

2020-09-29 22:25 UTC, StealthTech commented on src/components/Footer/Footer.css
> +}
Пустой строки нет :(

2020-09-29 22:25 UTC, StealthTech commented on src/components/Footer/Footer.css
> +    background-color: rgba(255, 255, 255, 0.7);
Давай все цвета в переменные?

2020-09-29 22:25 UTC, StealthTech commented on src/components/Footer/Footer.css
> +    color: #FFFFFF;
Цвет —> переменная

2020-09-29 22:25 UTC, StealthTech commented on src/components/BaseComponent.js
> +class BaseComponent {
Думаю, можно назвать просто `Component`

2020-09-29 22:25 UTC, StealthTech commented on src/components/Footer/Footer.js
> +        this.template = Handlebars.templates['Footer.hbs'];
Нравится такое решение 👍

2020-09-29 22:25 UTC, StealthTech commented on src/components/Footer/Footer.hbs
> +    <p class="footer__title">&copy 2020-2020 Flicks Box, Inc.</p>
Точка с запятой потерялась после `&copy`

2020-09-29 22:25 UTC, StealthTech commented on src/components/Footer/Footer.js
> +    onRender() {}
Зачем перегружать пустую функцию пустой функцией?

2020-09-29 22:25 UTC, StealthTech commented on src/components/Header/Header.js
> +    onRender() {}
То же самое, не понял

2020-09-29 22:25 UTC, StealthTech commented on src/components/Footer/Footer.js
> +        return this.template(this.context);
Может быть, это можно в `BaseComponent` перенести?

2020-09-29 22:25 UTC, StealthTech commented on src/components/Preview/Preview.hbs
> +</div>
Нет пустой строки

2020-09-29 22:25 UTC, StealthTech commented on src/components/Slider/Slider.css
> +    width: 16.666%;
Ауч. Почему так?

2020-09-29 22:25 UTC, StealthTech commented on src/components/Slider/Slider.css
> +    color: #FFFFFF;
Не забываем про цвета! Экономим себе нервы в будущем

2020-09-29 22:25 UTC, StealthTech commented on src/components/Preview/Preview.js
> +        this.template = Handlebars.templates['Preview.hbs'];
Можно вынести эту конструкцию в `BaseComponent` в какую-нибудь функцию и в `template` указывать только название шаблона

2020-09-29 22:25 UTC, StealthTech commented on src/consts/routes.js
> +const Paths = {
Я бы назвал это `routes`, тем более, что файл так и называется

2020-09-29 22:25 UTC, StealthTech commented on src/controllers/BaseController.js
> +class BaseController {
Может, просто `Controller`?

2020-09-29 22:25 UTC, StealthTech commented on src/index.js
> +(new Router)
Давай так не будем делать — лучше `const router`, и дальше уже вызывать то, что нужно

2020-09-29 22:25 UTC, StealthTech commented on src/index.js
> +    .register(Paths.MainPage, new MainController)
Скобки не потерялись?

2020-09-29 22:25 UTC, StealthTech commented on src/models/UserModel.js
> +
Если это заготовка на будущее, оставь TODO, пожалуйста

2020-09-29 22:25 UTC, StealthTech commented on src/services/EventBus.js
> +        this.listeners[event] = this.listeners[event] ? this.listeners[event] : [];
Не лучше ли `if (this.listeners[event] === undefined) { this.listeners[event] = [] }`

2020-09-29 22:25 UTC, StealthTech commented on src/views/BaseView.js
> +        data.forEach((obj) => Object.entries(obj).forEach((pair) => this.addToContext(pair[0], pair[1])));
Вместо `pair` можно `[key, value]`

Хотя пока не осознал, почему именно так, а не просто `{...obj}`

2020-09-30 14:45 UTC, yletamitlu commented on src/index.js
> +(new Router)
немного не понимаю, зачем нам его тут инстанс ?

2020-09-30 14:48 UTC, yletamitlu commented on src/components/Footer/Footer.js
> +        return this.template(this.context);
подразумевала, что в base только интерфейс - хотела переезжать на typescript после РК, там из интерфейса придется это вырезать снова

2020-09-30 14:52 UTC, yletamitlu commented on src/components/Slider/Slider.css
> +    width: 16.666%;
попробовала применить гриды, но проблема в том, что мне нужно, чтобы элементы прятались за экран для скролла, поэтому я говорю, что один будет занимать 16.666% - вынесу просто это в переменную наверное

2020-09-30 16:58 UTC, yletamitlu commented on src/services/EventBus.js
> +        this.listeners[event] = this.listeners[event] ? this.listeners[event] : [];
тернарный оператор больше нравится

2020-09-30 16:59 UTC, yletamitlu commented on src/views/BaseView.js
> +        data.forEach((obj) => Object.entries(obj).forEach((pair) => this.addToContext(pair[0], pair[1])));
попробовала с ...obj - чуть-чуть не то делает, что мне нужно было, добавляет эти элементы с ключами 0 и 1

2020-09-30 23:41 UTC, StealthTech approved these changes

2020-09-30 23:42 UTC, merged