FB-18: Регистрация в SPA
frontend-park-mail-ru/2020_2_Slash pull request #9
Opened 2020-10-02 23:20 UTC by butoly

Логику из ModalService по созданию компонент вынесу в отдельный класс Builder/Factory и выделю в отдельную компоненту форму.

2020-10-03 09:53 UTC, StealthTech requested changes

2020-10-03 09:53 UTC, StealthTech commented on src/components/Button/Button.css
> +    border: 1px solid #000000;
Цвета в переменные

2020-10-03 09:53 UTC, StealthTech commented on src/components/Input/Input.css
> +    background: #FAFAFA;
Цвета в переменные

2020-10-03 09:53 UTC, StealthTech commented on src/components/Input/Input.css
> +    color: white;
Цвета в переменные

2020-10-03 09:53 UTC, StealthTech commented on src/components/Popup/Popup.hbs
> +                        {{{this}}}
this?

2020-10-03 09:53 UTC, StealthTech commented on src/controllers/SignUpController.js
> +        EventBus.emit(Events.PathChanged, {
Выглядит, будто можно упростить это и if выше — тут все одинаковое кроме ключа misc. Можно его добавлять внутри if, а EventBus.emit вызывать в любом случае

2020-10-03 09:53 UTC, StealthTech commented on src/services/ModalService.js
> +            const signupPopup = new Popup({
Давай весь этот ифак до const signupPopup вынесем в отдельный файл условно popups/signup.js, и здесь только импортнем signupPopup?

2020-10-03 09:53 UTC, StealthTech commented on src/views/MainVIew/MainView.js
> +    constructor({title = '', context = {}} = {}) {
Почему теперь title по-умолчанию пустой?

2020-10-03 09:53 UTC, StealthTech commented on public/registration.html
>  <div class="application">
Зачем теперь нужен этот файл?

2020-10-03 16:31 UTC, butoly commented on src/components/Popup/Popup.hbs
> +                        {{{this}}}
![image](https://user-images.githubusercontent.com/31550348/94996721-f81c8880-05ae-11eb-86e0-bd48ebe85889.png).  
Вопрос решили

2020-10-04 08:20 UTC, StealthTech approved these changes

2020-10-04 09:27 UTC, merged